# Generated by Django 2.2.6 on 2019-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('ContactName', models.CharField(max_length=200)),
                ('ContactTitle', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
    ]
