# Generated by Django 2.2.6 on 2019-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('region_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_title', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_per_unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('units_in_stock', models.SmallIntegerField()),
                ('units_on_order', models.SmallIntegerField()),
                ('reorder_level', models.SmallIntegerField()),
                ('caregory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Category')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Suppliers')),
            ],
        ),
    ]
